../../example_design/rtl/prbs31_128bit.v
../../example_design/rtl/test_main_ctrl.v
../../rtl/pll/pll_50_400.v
../../rtl/ipsl_ddrc_apb_reset.v
../../rtl/ipsl_ddrc_reset_ctrl.v
../../rtl/ipsl_ddrphy_dll_update_ctrl.v
../../rtl/ipsl_ddrphy_reset_ctrl.v
../../rtl/ipsl_ddrphy_training_ctrl.v
../../rtl/ipsl_ddrphy_update_ctrl.v
../../rtl/ipsl_hmemc_ddrc_top.v
../../rtl/ipsl_hmemc_phy_top.v
../../rtl/ipsl_phy_io.v
../../ddr3.v
../../example_design/rtl/test_rd_ctrl_64bit.v
../../example_design/rtl/test_wr_ctrl_64bit.v
../../example_design/rtl/ipsl_hmemc_top_test.v
